CREATE TABLE IF NOT EXISTS `users` (
  `UUID`       VARCHAR(36)  NOT NULL,
  `FIRST_NAME` VARCHAR(128) NOT NULL,
  `LAST_NAME`  VARCHAR(128) NOT NULL,
  `EMAIL`      VARCHAR(128) NOT NULL,
  `PASSWORD`   VARCHAR(128) NOT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE INDEX `email_unique_index` (`EMAIL`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `conversations` (
  `UUID`            VARCHAR(36) NOT NULL,
  `USER_UUID`       VARCHAR(36) NOT NULL,
  `PARTICIPANT_IDS` VARCHAR(256) NOT NULL,
  `CREATED_DTM`     DATETIME    NOT NULL,
  PRIMARY KEY (`UUID`),
  FOREIGN KEY (`USER_UUID`) REFERENCES `users` (`UUID`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `messages` (
  `UUID`              VARCHAR(36) NOT NULL,
  `CONTENT`           MEDIUMTEXT DEFAULT NULL,
  `CREATED_DTM`       DATETIME    NOT NULL,
  `UPDATED_DTM`       DATETIME    NOT NULL,
  `CONVERSATION_UUID` VARCHAR(36) NOT NULL,

  PRIMARY KEY (`UUID`),
  FOREIGN KEY (`CONVERSATION_UUID`) REFERENCES `conversations` (`UUID`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;